name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "30 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - name: Generate SVG 1
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: ./profile-3d-contrib/conf1.json
          OUTPUT_PATH: ./profile-3d-contrib/profile-night-rainbow.svg
      - name: Generate SVG 2
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: ./profile-3d-contrib/conf2.json
          OUTPUT_PATH: ./profile-3d-contrib/profile-light.svg
      # 8 مرحله دیگر برای فایل‌های دیگر
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated multiple SVGs" || true
          git push
